from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^how_it_works/', TemplateView.as_view(template_name="core/how_it_works_salons.html"), name='salons_HIW'),
    url(r'^add_artist/$', 'glamazer.salons.views.add_artist', name='salons_add_artist'),
    url(r'^change_password/(?P<email_token>.*)', 'glamazer.users.views.change_password', name='change_password'),
    url(r'^forgotten_password/', 'glamazer.users.views.forgotten_password', name='forgotten_password'),
    url(r'^sign_up/$', 'glamazer.salons.views.sign_up', name='salons_sign_up'),
    url(r'^sign_up/facebook$', 'glamazer.salons.views.facebook_registration', name='salons_sign_up_facebook'),
    url(r'^gallery/$', 'glamazer.salons.views.gallery', name='salons_gallery'),
    url(r'^upload/$', 'glamazer.salons.views.upload', name='salons_upload'),
    url(r'^reassign/$', 'glamazer.salons.views.reassign', name='salons_artist_reassign'),
    url(r'^profile/$', 'glamazer.salons.views.profile', name='salons_profile'),
    url(r'^profile/(?P<salon_id>.*)/(?P<name>.*)$', 'glamazer.salons.views.profile', name='profile_salon'),
    url(r'^artists/delete/(?P<artist_id>.*)$', 'glamazer.salons.views.delete_artist', name='salons_artists_delete'),
    url(r'^artists/activate/(?P<artist_id>.*)$', 'glamazer.salons.views.activate', name='salons_artists_activate'),
    url(r'^artists/accept/(?P<artist_id>.*)$', 'glamazer.salons.views.artists_accept', name='salons_artists_accept'),
    url(r'^artists/reject/(?P<artist_id>.*)$', 'glamazer.salons.views.artists_reject', name='salons_artists_reject'),
    url(r'^artists/reject-fire/(?P<artist_id>.*)$', 'glamazer.salons.views.artists_reject_fire', name='salons_artists_reject_fire'),
    url(r'^settings/profile$', 'glamazer.salons.views.edit', name='salons_edit'),
    url(r'^settings/account$', 'glamazer.salons.views.account', name='edit_salons_account'),
    url(r'^settings/policy$', 'glamazer.salons.views.cancellation_policy', name='salons_cancellation_policy'),
    url(r'^settings/payments$', 'glamazer.salons.views.payments', name='salons_payments'),
    url(r'^management/artists$', 'glamazer.salons.views.artists', name='salons_artists'),
    url(r'^management/listings$', 'glamazer.salons.views.all_listings', name='salons_listings'),
    url(r'^management/schedule/(?P<artist_id>.*)$', 'glamazer.salons.views.salon_schedule', name='salons_schedule'),
    url(r'^management/calendar/(?P<artist_id>.*)$', 'glamazer.salons.views.calendar', name='salons_calendar'),
    url(r'^management/statistic$', 'glamazer.salons.views.stats', name='salons_statistic'),
    url(r'^management/widgets$', 'glamazer.widget.views.create_widget', name='salon_widgets'),
    url(r'^settings/widgets/toggle$', 'glamazer.widget.views.toggle_logo', name='salon_widgets_toggle'),
    url(r'^artists/settings/profile/(?P<artist_id>.*)$', 'glamazer.salons.views.edit_artist', name='salons_artists_edit'),
    url(r'^artists/settings/schedule/(?P<artist_id>.*)$', 'glamazer.salons.views.schedule', name='salons_artists_schedule'),
    url(r'^settings/delete_image$', 'glamazer.salons.views.delete_image', name='salons_delete_image'),
    url(r'^bookings/$', 'glamazer.salons.views.bookings', name='salons_bookings'),
    url(r'^bookings/report$', 'glamazer.users.views.report_problem', name='salons_report_booking'),
    url(r'^notifications/$', 'glamazer.notifications.views.show_notifications', name='salon_notifications'),
    url(r'^wallet/$', 'glamazer.salons.views.wallet', name='salons_wallet'),
    url(r'^withdraw/$', 'glamazer.salons.views.withdraw', name='salons_withdraw'),
    url(r'^get_chart_info/$', 'glamazer.salons.views.get_chart_info', name='salon_get_chart_info'),
)
